os: linux
dist: trusty

language: java
jdk:
  - oraclejdk8

env:
  - ENABLE_ASSERTION=true
  - ENABLE_ASSERTION=false

install: 
  - mvn clean install -DskipTests

script:
  - mvn clean test -DenableAssertions=`echo ${ENABLE_ASSERTION}`
