os: linux
dist: trusty

language: java
jdk:
  - oraclejdk8

env:
  - ENABLE_ASSERTION=true
  - ENABLE_ASSERTION=false

install: 
  - cd janino-parent
  - MAVEN_SKIP_RC=true mvn clean install -DskipTests

script:
  - MAVEN_SKIP_RC=true mvn test -DenableAssertions=`echo ${ENABLE_ASSERTION}` -DargLine="-Xss2m"
